### ISSUE TITLE
doesn't work ⊙﹏⊙∥

### ISSUE THREAD

**Issue by LetUsFlow** [Kevin-Konradi/Roguelite-Mages#1]
![grafik](https://user-images.githubusercontent.com/32359801/176198594-0451c602-3413-414e-921b-61eba3ee9a88.png)
I get ewwor (；′⌒`)
pwease fix

**Comment by LetUsFlow** [comment]
´
![grafik](https://user-images.githubusercontent.com/32359801/176199243-958e781e-4439-4fbe-bc46-53708e47b1a7.png)
now i get another ewwow (ノへ￣、) (┬┬﹏┬┬)

**Comment by Kevin-Konradi** [comment]
fuck you

**Comment by LetUsFlow** [comment]
u too φ(*￣0￣)

**Comment by Kevin-Konradi** [comment]
Amethyst ist doof. Ist gut, dass Code nicht funktioniert.
Wir in bevy neu geschrieben King
